---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Java 17
  apt:
    name: "{{ java_package }}"
    state: present

- name: Verify Java installation
  command: java -version
  register: java_version
  changed_when: false

- name: Display Java version
  debug:
    msg: "{{ java_version.stderr }}"